package view;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import model.User;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author xiaopu
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     * @param
     * @param user
     */
    public MainPanel(User user) {
        this.user = user;
        setLayout(new CardLayout());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        securityButton = new JButton();
        fireAlarmButton = new JButton();
    //    userButton = new JButton();
     //   goBackButton = new javax.swing.JButton();

        setPreferredSize(new Dimension(1200, 750));
        setSize(new Dimension(1200, 750));

        securityButton.setFont(new Font("Lucida Grande", 0, 24)); // NOI18N
        securityButton.setText("Security System ");
        securityButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                securityButtonActionPerformed(evt);
            }
        });

        fireAlarmButton.setFont(new Font("Lucida Grande", 0, 24)); // NOI18N
        fireAlarmButton.setText("Fire Alarm System");
        fireAlarmButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                fireAlarmButtonActionPerformed(evt);
            }
        });

//        userButton.setText("User");
//        userButton.addActionListener(new ActionListener() {
//            public void actionPerformed(ActionEvent evt) {
//                userButtonActionPerformed(evt);
//            }
//        });

     //   goBackButton.setText("go back");
    //    goBackButton.addActionListener(new java.awt.event.ActionListener() {
      //      public void actionPerformed(java.awt.event.ActionEvent evt) {
     //           goBackButtonActionPerformed(evt);
   //         }
      //  });

        layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(securityButton, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194)
                .addComponent(fireAlarmButton, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
               // .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               // .addComponent(userButton, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                //.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    //.addComponent(userButton, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
                    //.addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(securityButton, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE)
                    .addComponent(fireAlarmButton, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
                .addGap(300, 300, 300))
        );
    }// </editor-fold>//GEN-END:initComponents

//    private void goBackButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
//        // TODO add your handling code here:
//        SignInFrame signInFrame = new SignInFrame();
//        signInFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
//        signInFrame.setVisible(true);
//
//
//    }//GEN-LAST:event_goBackButtonActionPerformed

//    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
//        // TODO add your handling code here:
//        DisplayPanel.getDisplayPanel(user).getCards().show(DisplayPanel.getDisplayPanel(user), "userPanel");
//
//
//    }//GEN-LAST:event_userButtonActionPerformed

    private void fireAlarmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fireAlarmButtonActionPerformed
        // TODO add your handling code here:
        DisplayPanel.getDisplayPanel(user).getCards().show(DisplayPanel.getDisplayPanel(user), "fireAlarmPanel");

    }//GEN-LAST:event_fireAlarmButtonActionPerformed

    private void securityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityButtonActionPerformed
        // TODO add your handling code here:
        DisplayPanel.getDisplayPanel(user).getCards().show(DisplayPanel.getDisplayPanel(user), "securityPanel");

    }//GEN-LAST:event_securityButtonActionPerformed

    public static MainPanel getMainPanel(User user) {
        if (mainPanel == null) {
            mainPanel = new MainPanel(user);
        }
        return mainPanel;
    }

    public GroupLayout getLayout() {
        return layout;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GroupLayout layout;
    private static MainPanel mainPanel;
    private javax.swing.JButton fireAlarmButton;
    //private javax.swing.JButton goBackButton;
    private javax.swing.JButton securityButton;
    //private javax.swing.JButton userButton;
    // End of variables declaration//GEN-END:variables
    private User user;
}
